version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(filename)s:%(lineno)d'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: app.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    level: DEBUG
  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    level: ERROR
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: false
root:
  handlers: [console, file, error_file]
  level: DEBUG
